version: "3"
services:
  web:
    # 1. CHANGED: Replaced 'build: .' with an image name
    image: abdullah153/python-redis-app:latest
    # 2. ADDED: Restart policy
    restart: always
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"
    # 3. ADDED: Ports for redis
    ports:
      - "6379:6379"