name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_REPO }} # Ensure this secret exists
      TAG: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Tag and Push Docker images
        run: |
          # Create a short SHA variable
          SHA_TAG=${GITHUB_SHA::8}
          
          # Tag the image with the short SHA
          docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.IMAGE_NAME }}:$SHA_TAG
          
          # Push both the 'latest' tag and the 'SHA' tag
          docker push ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker push ${{ env.IMAGE_NAME }}:$SHA_TAG
